config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root "posts#index"

  resources :categories 

  resources :posts  do
    resources :likes
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable

  has_many :posts
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts

  validates_presence_of :name
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :admin
  has_and_belongs_to_many :categories
  has_many :likes
  validates_presence_of :title, :body

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :likes

  # validates_presence_of :name, :age
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @categories = Category.new
  end

  def create
    @category = Category.new
    @category.post = @category

    if @category.save
      redirect_to post_categories_path(@post, @category), notice: "New Post Created"
    else
      render :new
    end
  end

  def destroy
  end

  def show
    @category = Category.find( params[:id] )
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @likes = Like.all
  end

  def create
    post = Post.find( params[:post_id] )

    if like = Like.find_by( post: post, user: current_user )
       like.destroy
    else
       like = Like.new( post: post, user: current_user )
       like.save
    end

    redirect_to posts_path
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
 def index
   @posts = Post.all

   respond_to do |format|
   format.html
   format.json { render json: @posts }
   end
 end

 def show
   @post = Post.find( params[:id] )
 end

 def new
   @post = Post.new

   respond_to do |format|
     format.html
     format.json  { render :json => @post }
   end
 end

 def create
   @post = Post.new(post_params)

   if @post.save
       redirect_to posts_path, :notice => "Your post was saved"
   else
       render :new
   end
 end

 def update
   @post = Post.find(params[:id])

   if @post.update(params[:post].permit(:title, :body))
     redirect_to @post
   else
     render 'edit'
   end
 end

 def edit
   @post = Post.find( params[:id] )
 end

 def destroy
   @post = Post.find( params[:id])
   @post.destroy
   respond_to do |format|
     format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.'}
     format.json { head :no_content }
   end
 end

 def user
     @user = User.find( params[:user_id] )

     @posts = Post.where( user: @user ).order( created_at: :desc )

     @likes = @user.likes.joins( :post ).order( "posts.created_at DESC" )
  end

 private
 def post_params
      params.require(:post).permit(:title, :body, :id, :image)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/categories/_category.html.erb
<div class="category">
   <h3><%= category.name %></h3>
</div>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories</h1>
<h3>H3 for testing</h3>
<p>Find me in app/views/categories/index.html.erb</p>
<p>This are all the Categories:</p>

<%= render @categories %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- <header class="navbar navbar-fixed-top navbar-default"> -->
      <title>Blog</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <!-- CSS  -->
    <link href='https://fonts.googleapis.com/css?family=Cabin:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <div class="container">
        <nav>
          <div class="nav-wrapper">
            <a href="#" class="brand-logo">Logo</a>
              <ul id="nav-mobile" class="right hide-on-med-and-down">
                  <% if !user_signed_in? %>
                 <li><%= link_to "Log In", new_user_session_path %></li>
                 <% else %>
                 <li><%= current_user.email %></span></li>
                 <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
                 <% end %>
                <li><%= link_to "Posts", posts_path %></li>
                 <li><a href="sass.html"><i class="material-icons">search</i></a></li>
                 <li><a href="badges.html"><i class="material-icons">view_module</i></a></li>
                 <li><a href="collapsible.html"><i class="material-icons">refresh</i></a></li>
                 <li><a href="mobile.html"><i class="material-icons">more_vert</i></a></li>
              </ul>
        </nav>
      </div>
    </div>
    </header>
  </head>
<body>
  <%= yield %>
</body>
  <footer class="page-footer">
              <div class="container">
                <div class="row">
                  <div class="col l6 s12">
                    <h5 class="white-text">Contact me?</h5>
                    <p class="grey-text text-lighten-4">I can be reached in serveal ways. Shoot me an email now</p>
                  </div>
                  <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Want to know more?</h5>
                    <ul>
                      <li><a class="grey-text text-lighten-3" href="#!">Ruby On Rails</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">React.js</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">Javascript</a></li>
                      <li><a class="grey-text text-lighten-3" href="#!">HTML & CSS</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="footer-copyright">
                <div class="container">
                © 2016 Copyright MB
                <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
                </div>
              </div>
            </footer>
</html>

app/views/posts/_form.html.erb
<h1> Add a new Post!</h1>

  <p>please add your new post here!</p>

  <%= form_for Post.new do |f| %>
  
  <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :text %><br>
      <%= f.text_area :body %>
    </div>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </div>
    <div class="col-xs-4">
      <%= f.submit "Create", class: "btn" %>
    </div>

  <% end %>


  ​

app/views/posts/_post.html.erb
<div class="col-xs-8">
   <p>
     <h3><%= post.title %></h3>
      <h4><%= post.body %></h4>
      <h4><%= post.image %></h4>

      <% @posts.each do |post| %>
          <p><%= link_to post.title, post_path( post.id ) %></p>
      <% end %>

      <% liked = Like.find_by( post: post, user: current_user ) != nil %>
      <% btn_color = liked ? "warning" : "default" %>

      <%= link_to "ツ", post_likes_path( post ), method: :post, class: "btn btn-#{btn_color} btn-xs", disabled: !user_signed_in? %>
      <%= post.likes.count %>

   </p>
 </div>

<center>
<div class="post">
   <div class="row">
        <div class="col s8 m5">
          <div class="card">
            <div class="card-image">
              <img src="http://mwwebdesign.nl/wp-content/uploads/2011/05/over-mwwebdesign.jpg">
              <img src="http://www.pimp-mysite.nl/wp-content/uploads/2015/12/1.jpg">
              <span class="card-title"><%= post.title %></span>
            </div>
            <div class="card-content">
              <p><%= post.body %></p>
            </div>
            <div class="card-action">
              <a href="#">This is a link</a>
        </div>
      </div>
      <!-- <div class="row">
           <div class="col s8 m5">
             <div class="card">
               <div class="card-image">
                 <img src="http://www.pimp-mysite.nl/wp-content/uploads/2015/12/1.jpg">
                 <span class="card-title"><%= post.title %></span>
               </div>
               <div class="card-content">
                 <p><%= post.body %></p>
               </div>
               <div class="card-action">
                 <a href="#">This is a link</a>
               </div> -->
               </div>
             </div>
           </div>
         </div>
    </div>




</center>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

<%= form_for @post do |f| %>
<div class= "input">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class= "input">
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>

<div class= "actions">
<%= f.submit %>
</div>
<% end %>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts</h1>

<p>Some posts</p>

<%= render @posts %>

app/views/posts/new.html.erb
<h1> Add a new Post!</h1>

<% if admin_signed_in? %>

<%= render "form" %>


<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

<%= image_tag @post.image_url.to_s, class: 'bg' %>

<div class="content">
<h1><%= @post.title %></h1>

<p>
  <%= @post.body %>
</p>

<p>
   <% @post.categories.each do |categorie| %>
       <%= link_to "#{categorie.title}", genre, class: "btn btn-primary btn-xs" %>
   <% end %>
</p>
</div>

app/views/posts/user.html.erb
<h1><%= @user.handle %></h1>
<br>


<h1>likes</h1>
<br>

<% @likes.each do |like| %>
   <% if like.post.user_id != @user.id %>
      <h4><%= like.post.content %></h4>
   <% end %>
<% end %>